# Serverless Framework configuration for AWS Lambda deployment
service: pr-manager-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
  httpApi:
    cors:
      allowedOrigins:
        - https://your-amplify-domain.amplifyapp.com
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

package:
  patterns:
    - 'dist/**'
    - 'node_modules/**'
    - '!src/**'
    - '!*.ts'
    - '!tsconfig.json'